#!/usr/bin/env python

import os
import subprocess
import sys
from os.path import join as opj

#Try to locate sphinx-build executable
if 'ADFHOME' in os.environ:
    command = opj(os.path.expandvars('$ADFHOME'), 'bin' ,'pythonbase', 'bin', 'sphinx-build')
else:
    null = open(os.devnull, 'wb')
    try:
        subprocess.call(['sphinx-build','--version'], stdout=null, stderr=null)
        command = 'sphinx-build'
    except OSError:
        try:
            subprocess.call(['sphinx-build2','--version'], stdout=null, stderr=null)
            command = 'sphinx-build2'
        except OSError:
            print('Error: Sphinx executable not found!')
            print('Make sure ')
            null.close()
            sys.exit(0)
    null.close()

location = os.path.dirname(os.path.realpath(__file__))
#Source of documentation should be located in "source" subfolder next to this script
source = opj(location, 'source')

#Target can be given as command line argument, if not the "build" subfolder is used
if len(sys.argv) > 1:
    target = sys.argv[1]
else:
    target = opj(location, 'build')

subprocess.call([command, source, target])
